ARG GO_VERSION=1.26.0
FROM golang:${GO_VERSION}-alpine AS build

RUN apk update && apk upgrade && apk add --no-cache git

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /out/clamav-rest .

FROM golang:${GO_VERSION}-alpine AS test

RUN apk update && apk upgrade && apk add --no-cache \
    bash \
    clamav \
    clamav-libunrar \
    curl \
    jq \
    logrotate \
    openssl \
    tzdata

COPY clamavlogrotate /etc/logrotate.d/clamav

ENV TZ=Europe/Zurich

RUN mkdir -p \
    /etc/ssl/clamav-rest \
    /clamav/etc \
    /clamav/data \
    /clamav/test \
    /clamav/tmp \
    /run/clamav

# Configure clamAV to run in foreground with port 3310
RUN sed -i 's/^#Foreground .*$/Foreground yes/g' /etc/clamav/clamd.conf \
    && sed -i 's/^#TCPSocket .*$/TCPSocket 3310/g' /etc/clamav/clamd.conf \
    && sed -i 's/^#Foreground .*$/Foreground yes/g' /etc/clamav/freshclam.conf

RUN freshclam --quiet --no-dns

COPY entrypoint.sh /usr/bin/
COPY --from=build /out/clamav-rest /usr/bin/clamav-rest

RUN chown -R clamav:clamav /clamav \
    && chown -R clamav:clamav /var/log/clamav \
    && chown -R clamav:clamav /run/clamav \
    && chown -R clamav:clamav /etc/ssl/clamav-rest

# Add test data to test the /scanPath endpoint
RUN mkdir -p /clamav/tmp/ok /clamav/tmp/virus && \
echo 'hello world' > /clamav/tmp/ok/test.txt

COPY eicar.test /clamav/tmp/virus/

ENV PORT=9000
ENV SSL_PORT=9443
ENV MAX_SCAN_SIZE=100M
ENV MAX_FILE_SIZE=25M
ENV MAX_RECURSION=16
ENV MAX_FILES=10000
ENV MAX_EMBEDDEDPE=10M
ENV MAX_HTMLNORMALIZE=10M
ENV MAX_HTMLNOTAGS=2M
ENV MAX_SCRIPTNORMALIZE=5M
ENV MAX_ZIPTYPERCG=1M
ENV MAX_PARTITIONS=50
ENV MAX_ICONSPE=100
ENV MAX_RECONNECT_TIME=30
ENV PCRE_MATCHLIMIT=100000
ENV PCRE_RECMATCHLIMIT=2000
ENV SIGNATURE_CHECKS=2
ENV ALLOW_ORIGINS=*
ENV GOCACHE=/clamav/test/.cache/go-build
ENV GOMODCACHE=/clamav/test/.cache/go-mod

WORKDIR /opt/clamav-rest

COPY go.mod go.sum ./
COPY tests/go-test ./tests/go-test
COPY entrypoint_tests.sh run-go-tests ./

RUN chmod 0755 /opt/clamav-rest/entrypoint_tests.sh /opt/clamav-rest/run-go-tests \
    && mkdir -p "$GOCACHE" "$GOMODCACHE" \
    && chown -R clamav:clamav /clamav/test

USER clamav
ENTRYPOINT [ "/opt/clamav-rest/entrypoint_tests.sh" ]
CMD [ "test" ]
