FROM golang:alpine3.23 AS build

# Update libraries
RUN apk update && apk upgrade

# Set workdir
WORKDIR /go/src

# Build go package
ADD . /go/src/clamav-rest/
RUN cd /go/src/clamav-rest && go mod tidy && go build -v
#FROM docker.io/python:3-alpine3.23

# Copy compiled clamav-rest binary from build container to production container
RUN cp /go/src/clamav-rest/clamav-rest /usr/bin/ 
#--from=build

# Update & Install tzdata
RUN apk update && apk upgrade && apk add --no-cache tzdata

# Enable Bash & logrotate
RUN apk add bash logrotate

COPY clamavlogrotate /etc/logrotate.d/clamav

# Set timezone to Europe/Zurich
ENV TZ=Europe/Zurich

ADD ./server.* /etc/ssl/clamav-rest/

# Install ClamAV
RUN apk --no-cache add clamav go clamav-libunrar jq \
    && mkdir /run/clamav \
    && chown clamav:clamav /run/clamav 
# cURL added for tests. Comment this out in production
RUN apk --no-cache add curl

# Configure clamAV to run in foreground with port 3310
RUN sed -i 's/^#Foreground .*$/Foreground yes/g' /etc/clamav/clamd.conf \
    && sed -i 's/^#TCPSocket .*$/TCPSocket 3310/g' /etc/clamav/clamd.conf \
    && sed -i 's/^#Foreground .*$/Foreground yes/g' /etc/clamav/freshclam.conf

RUN freshclam --quiet --no-dns

COPY entrypoint.sh /usr/bin/

RUN mkdir -p /clamav/etc \
    && mkdir -p /clamav/data \
    && mkdir -p /clamav/tmp \
    && mkdir -p /clamav/test

RUN chown -R clamav:clamav /clamav \
    && chown -R clamav:clamav /var/log/clamav \
    && chown -R clamav:clamav /run/clamav 

# Add test data to test the /scanPath endpoint
RUN mkdir -p /clamav/tmp/ok /clamav/tmp/virus && \
echo 'hello world' > /clamav/tmp/ok/test.txt

COPY eicar.test /clamav/tmp/virus/

# Make go tests cache directory writable
RUN mkdir -p /go/pkg/mod/cache  \
    && ln -s /clamav/test /go/pkg/mod/cache/download \
    && chown -R clamav:clamav /go/pkg/mod/cache

ENV PORT=9000
ENV SSL_PORT=9443
ENV MAX_SCAN_SIZE=100M
ENV MAX_FILE_SIZE=25M
ENV MAX_RECURSION=16
ENV MAX_FILES=10000
ENV MAX_EMBEDDEDPE=10M
ENV MAX_HTMLNORMALIZE=10M
ENV MAX_HTMLNOTAGS=2M
ENV MAX_SCRIPTNORMALIZE=5M
ENV MAX_ZIPTYPERCG=1M
ENV MAX_PARTITIONS=50
ENV MAX_ICONSPE=100
ENV MAX_RECONNECT_TIME=30
ENV PCRE_MATCHLIMIT=100000
ENV PCRE_RECMATCHLIMIT=2000
ENV SIGNATURE_CHECKS=2
ENV ALLOW_ORIGINS=*

USER clamav


#FROM docker.io/python:3-alpine

WORKDIR /opt/clamav-rest
COPY . .
ADD --chmod=0755 ./run-tests .

ENTRYPOINT [ "/opt/clamav-rest/entrypoint_tests.sh" ]
CMD [ "test" ]
