#!/bin/bash


until curl -s -f -o /dev/null "http://localhost:9000/"
do
  echo "Tests are waiting for the rest bridge to start..."
  sleep 5
done

res=$(go test -json ./...)

failedTestOutput=$(printf '%s\n' "$res" | jq -r 'select(.Action=="fail" and .Test) | .Test')
okTestOutput=$(printf '%s\n' "$res" | jq -r 'select(.Action=="pass" and .Test) | .Test')
numberOfFailedTests=$(echo "$failedTestOutput" | wc -l | awk '{print $1}')

# uncomment to get verbose test output:
#echo "$res"

echo "Pass:"
echo "$okTestOutput"
if [[ $failedTestOutput ]]
then
  echo "Fail:"
  echo "$failedTestOutput"
else
  numberOfFailedTests=""
fi
exit $(($numberOfFailedTests))
